name: newsnow
description: A news app
publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: ">=2.16.0 <3.0.0"

dependencies:
  another_flushbar: ^1.10.28
  bloc: ^8.0.3
  cached_network_image: ^3.2.0
  cupertino_icons: ^1.0.2
  dartz: ^0.10.1
  device_preview: ^1.0.0
  dio: ^4.0.6
  dio_smart_retry: ^1.2.0
  equatable: ^2.0.3
  flutter:
    sdk: flutter
  flutter_bloc: ^8.0.1
  flutter_dotenv: ^5.0.2
  flutter_staggered_grid_view: ^0.6.1
  flutter_svg: ^1.0.3
  freezed_annotation: ^1.1.0
  gap: ^2.0.0
  get_it: ^7.2.0
  http: ^0.13.4
  injectable: ^1.5.3
  internet_connection_checker: ^0.0.1+3
  intl: ^0.17.0
  json_annotation: ^4.5.0
  logger: ^1.1.0
  retrofit: ^3.0.1+1
  retry: ^3.1.0
  

dev_dependencies:
  # bloc_test: ^9.0.3
  build_runner: ^2.1.10
  flutter_lints: ^1.0.0
  flutter_test:
    sdk: flutter

  freezed: ^1.1.1
  injectable_generator: ^1.5.3
  json_serializable: ^6.2.0
  retrofit_generator: ^4.0.1
  very_good_analysis: ^2.4.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/icons/
    - .env

  fonts:
    - family: Roboto
      fonts:
        - asset: assets/fonts/roboto/Roboto-Black.ttf
        - asset: assets/fonts/roboto/Roboto-Bold.ttf
        - asset: assets/fonts/roboto/Roboto-Medium.ttf
        - asset: assets/fonts/roboto/Roboto-Regular.ttf
        - asset: assets/fonts/roboto/Roboto-Thin.ttf
    - family: Playfair Display
      fonts:
        - asset: assets/fonts/playfair_display/PlayfairDisplay-Italic-VariableFont_wght.ttf
        - asset: assets/fonts/playfair_display/PlayfairDisplay-VariableFont_wght.ttf
 
